version: '3.6'
name: 'mysql-5'

volumes:
  mysql-5_data:
    name: "mysql-5_data"
    driver: local

services:
  mysql-5.7:
    image: mysql:5.7.44-oracle
    container_name: mysql-5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql-5_data:/var/lib/mysql
