version: '3.6'
name: 'mysql-8'

volumes:
  mysql-8_data:
    name: "mysql-8_data"
    driver: local

services:
  mysql-8.2:
    image: mysql:8.2.0-oracle
    container_name: mysql-8.2
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - mysql-8_data:/var/lib/mysql
